<?php if ($block->getData('title')) :
    $apiKey = "07d0ec504bc43d38023e3e6eb08b6067";
    $cityId = ["1581130", "1580240", "1566083"];
?>
    <div class="weather-container" id="weather">
        <div class="link-weather">
            <a href="#weather">Weather</a>
        </div>
        <?php
        for ($i = 0; $i < 3; $i++) {


            // $googleApiUrl = "http://api.openweathermap.org/data/2.5/weather?id=" . $cityId[$i] . "&lang=en&units=metric&APPID=" . $apiKey;
            $googleApiUrl = "http://api.openweathermap.org/data/2.5/forecast?lat=21.0294498&lon=105.8544441&appid=27a882c3ec9d8e70262bf880f1a463e4&units=metric";

            $ch = curl_init();

            curl_setopt($ch, CURLOPT_HEADER, 0);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
            curl_setopt($ch, CURLOPT_URL, $googleApiUrl);
            curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
            curl_setopt($ch, CURLOPT_VERBOSE, 0);
            curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
            $response = curl_exec($ch);

            curl_close($ch);
            $data = json_decode($response)->list[$i];
            $currentTime = time();


        ?>

            <style>
                .weather-container {
                    border: #E0E0E0 1px solid;
                    border-radius: 5px;
                    display: inline-block;
                    /* width: 300px; */
                    padding-left: 10px;
                    margin-left: 10px;

                }

                .container-weather {
                    font-family: Arial;
                    font-size: 16px;
                    color: #929292;
                    float: left;
                    display: block;
                    /* width: 30%; */
                    margin-right: 10px;
                }

                .report-container {
                    padding-top: 10px;
                    width: 30%;
                    margin: 0 auto;
                    display: inline-block;
                }

                .weather-icon {
                    vertical-align: middle;
                    margin-right: 20px;
                }

                .weather-forecast {
                    color: #212121;
                    font-size: 18px;
                    font-weight: bold;
                    margin: 5px 0px;
                }

                span.min-temperature {
                    margin-left: 15px;
                    color: #929292;
                }

                .time {
                    line-height: 25px;
                }

                .link-weather>a {
                    text-decoration: none;
                    background-color: #badc58;
                    color: #ffffff;
                    position: fixed;
                    border-radius: 5px 0px 0px 5px;
                    right: 0px;
                    top: 260px;
                    font-size: 18px;
                    font-weight: bold;
                    padding: 10px 10px 10px 5px;
                    width: 100px;
                    z-index: 2;
                }

                .link-weather>a:hover {
                    background-color: #f1c40f;
                }
            </style>

            <div class="report-container">
                <h2 style="margin-bottom:2px;">Ha Noi</h2>
                <div class="time">
                    <div><?php echo date("jS F, Y", $currentTime); ?></div>
                    <div><?php echo ucwords($data->weather[0]->description); ?></div>
                </div>
                <div class="weather-forecast">
                    <img src="http://openweathermap.org/img/w/<?php echo $data->weather[0]->icon; ?>.png" class="weather-icon" /> <?php echo $data->main->temp_max; ?>°C <span class="min-temperature"><?php echo " " . $data->main->temp_min; ?>°C</span>
                </div>
                <div class="time">
                    <div>Humidity: <?php echo $data->main->humidity; ?> %</div>
                    <div>Wind: <?php echo $data->wind->speed; ?> km/h</div>
                </div>
            </div>
        <?php } ?>
    <?php endif; ?>